### ISSUE TITLE
Usage: change circuit more often

### ISSUE THREAD

**Issue by konsumer** [dperson/torproxy#17]
This is a usage question, so feel free to send me to a forum or something. I couldn't find any for this docker container.

I want to refresh my IP more often. I tried making a docker-compose that looks like this:

```yml
version: '3'
services:
  tor:
    image: dperson/torproxy
    restart: unless-stopped
    environment:
      - TOR_MaxCircuitDirtiness=1
      - TOR_NewCircuitPeriod=1
      - TOR_EnforceDistinctSubnets=1
      - LOCATION=US
  app:
    build: .
    restart: unless-stopped
    environment:
      - PORT=3000
    ports:
      - 3000:3000
```

My app is a simple express service, like this:

```js
// get info about running server
app.get('/info', (req, res) => {
  const { name, version } = pkg
  request({url: 'http://jsonip.com/', proxy: 'http://tor:8118'}, (err, response, body) => {
    if (err) {
      return res.status(500).json(err)
    }
    const { ip } = JSON.parse(body)
    res.json({
      name,
      version,
      ip
    })
  })
})
```

I get an IP that is different from my own, but it doesn't change between requests very often:

Example:
```json
{
  "name": "data-proxy",
  "version": "1.0.0",
  "ip": "104.223.123.98"
}
```
