### ISSUE TITLE
Can't set --net host on docker-compose

### ISSUE THREAD

**Issue by carlastabile** [dperson/torproxy#23]
Is it possible to set this option on the docker-compose.yml? I'm trying to do it like this: 

```
tor:
  image: dperson/torproxy
  volumes:
    - ./torrc:/etc/tor/torrc
  expose:
    - 9050
    - 8118
  entrypoint: torproxy.sh
  command:
    - "--net host -p 8118:8118 -p 9050:9050"
```
