### ISSUE TITLE
Container not starting

### ISSUE THREAD

**Issue by ssrahul96** [dperson/torproxy#58]
Hi,

I am using [dockstarter](https://dockstarter.com/) in raspberry pi 3.

I ve added the below config in dockstarter docker-compose.override.yml

```
  torproxy:
    image: dperson/torproxy:latest
    container_name: torproxy
    ports:
      - "9050:9050"
      - "8118:8118"
    environment:
      - TORUSER=pi
      - TOR_NewCircuitPeriod=400
      - TZ=${TZ}
```
I ve tired without TORUSER as well as TORUSER=root as env variables.

The container stops as soon it starts.
